# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
