# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reward',
            field=models.DecimalField(decimal_places=9, default=0.6, max_digits=10),
        ),
    ]
