# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='for_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
