# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180307_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
