# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_settings_show_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reward',
            field=models.IntegerField(default=6),
        ),
    ]
