# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turns', '0019_auto_20180301_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_length', models.IntegerField(default=1)),
                ('quality_length', models.IntegerField(default=1)),
                ('context_length', models.IntegerField(default=5)),
                ('discount', models.DecimalField(decimal_places=9, default='0.99', max_digits=10)),
                ('epsilon', models.DecimalField(decimal_places=9, default=0, max_digits=10)),
                ('batch_size', models.IntegerField(default=10)),
                ('episode_size', models.IntegerField(default=50)),
                ('test_ratio', models.DecimalField(decimal_places=9, default=0.1, max_digits=10)),
                ('seconds_for_terminal', models.IntegerField(default=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action_intents', models.ManyToManyField(related_name='_configuration_action_intents_+', to='turns.Intent')),
                ('didnt_understand_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('for_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='response_templates',
            field=models.ManyToManyField(to='config.ResponseTemplate'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='state_intents',
            field=models.ManyToManyField(related_name='_configuration_state_intents_+', to='turns.Intent'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='unknown_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.Intent'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='user_profile_variable_names',
            field=models.ManyToManyField(related_name='_configuration_user_profile_variable_names_+', to='config.UserProfileVariable'),
        ),
    ]
