# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180405_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='action_intents',
            field=models.ManyToManyField(related_name='_configuration_action_intents_+', to='turns.IntentTemplate'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='didnt_understand_intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.IntentTemplate'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='state_intents',
            field=models.ManyToManyField(related_name='_configuration_state_intents_+', to='turns.IntentTemplate'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='unknown_intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.IntentTemplate'),
        ),
        migrations.AlterField(
            model_name='responsetemplate',
            name='for_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='turns.IntentTemplate'),
        ),
    ]
