# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateTimeField(auto_now_add=True)),
                ('with_user', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='IntentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_flow_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_flow_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('sentiment', models.DecimalField(decimal_places=9, max_digits=10)),
                ('said_on', models.DateTimeField(auto_now_add=True)),
                ('said_by', models.CharField(max_length=64)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Intent')),
                ('said_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Dialogue')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='SlotTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_flow_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
                ('is_list', models.BooleanField(default=False)),
                ('intent_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.IntentTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_flow_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active_player', models.BooleanField()),
                ('favourite_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Player')),
                ('favourite_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Team')),
            ],
        ),
        migrations.AddField(
            model_name='slottemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.SlotType'),
        ),
        migrations.AddField(
            model_name='slot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.SlotTemplate'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.Topic'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turns.UserProfile'),
        ),
        migrations.AddField(
            model_name='intent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.IntentTemplate'),
        ),
    ]
