# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentiment',
            field=models.DecimalField(decimal_places=9, max_digits=10, null=True),
        ),
    ]
