# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_auto_20171219_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.Intent'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.Topic'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turns.UserProfile'),
        ),
    ]
