# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0003_auto_20171219_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.Player'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active_player',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
