# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0006_auto_20180109_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dialog_flow_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dialog_flow_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_favourite_player',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_favourite_team',
            field=models.NullBooleanField(),
        ),
    ]
