# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0007_auto_20180109_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
