# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0008_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='reward',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
