# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0009_sentence_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='terminal',
            field=models.BooleanField(default=False),
        ),
    ]
