# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0011_sentence_raw_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='used_in_training',
            field=models.BooleanField(default=False),
        ),
    ]
