# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0012_sentence_used_in_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slottemplate',
            name='intent_template',
        ),
        migrations.RemoveField(
            model_name='slottemplate',
            name='type',
        ),
        migrations.AddField(
            model_name='intenttemplate',
            name='expected_entities',
            field=models.ManyToManyField(to='turns.SlotTemplate'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='raw_sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Message'),
        ),
        migrations.DeleteModel(
            name='SlotType',
        ),
    ]
