# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0013_auto_20180228_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_list', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Slot',
            new_name='Parameter',
        ),
        migrations.RemoveField(
            model_name='intenttemplate',
            name='expected_entities',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turns.ParameterTemplate'),
        ),
        migrations.DeleteModel(
            name='SlotTemplate',
        ),
        migrations.AddField(
            model_name='intenttemplate',
            name='parameters',
            field=models.ManyToManyField(to='turns.ParameterTemplate'),
        ),
    ]
