# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0014_auto_20180228_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intenttemplate',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parametertemplate',
            name='intent_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turns.IntentTemplate'),
        ),
    ]
