# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0016_auto_20180228_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertemplate',
            name='intent_template',
        ),
        migrations.AddField(
            model_name='parametertemplate',
            name='intent_template',
            field=models.ManyToManyField(to='turns.IntentTemplate'),
        ),
    ]
