# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0018_auto_20180228_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turns.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='shoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turns.Shoe'),
        ),
    ]
