# Generated by Django 2.0.2 on 2018-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0019_auto_20180301_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='created_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reward',
            field=models.DecimalField(decimal_places=9, default=0.6, max_digits=10),
        ),
    ]
